name: Test

on:
  pull_request:
    branches:
      - master

jobs:
  test-unit:
    name: Unit test
    runs-on: [ubuntu-18.04]
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v1
        with:
          go-version: 1.19
      - name: Check-out code
        uses: actions/checkout@v2
      - name: Run unit tests
        run: make test-unit
